// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmzWliBQM6wL5fZSNs6Yra4t8PM98baQ',
    appId: '1:493268505144:web:3191223ed3c1024d2fcccd',
    messagingSenderId: '493268505144',
    projectId: 'mytodo-f50b8',
    authDomain: 'mytodo-f50b8.firebaseapp.com',
    storageBucket: 'mytodo-f50b8.appspot.com',
    measurementId: 'G-NBT5V40JPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwzWcvxj8ICbMdyKHFn6plYg1aO9JojDA',
    appId: '1:493268505144:android:c6a7175caeb11daa2fcccd',
    messagingSenderId: '493268505144',
    projectId: 'mytodo-f50b8',
    storageBucket: 'mytodo-f50b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLWGVQXmToPZvnaZq6ajp8ms_g6EnR7U',
    appId: '1:493268505144:ios:0c282f70c0e6e2ed2fcccd',
    messagingSenderId: '493268505144',
    projectId: 'mytodo-f50b8',
    storageBucket: 'mytodo-f50b8.appspot.com',
    iosBundleId: 'com.example.mytodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwLWGVQXmToPZvnaZq6ajp8ms_g6EnR7U',
    appId: '1:493268505144:ios:0c282f70c0e6e2ed2fcccd',
    messagingSenderId: '493268505144',
    projectId: 'mytodo-f50b8',
    storageBucket: 'mytodo-f50b8.appspot.com',
    iosBundleId: 'com.example.mytodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALmzWliBQM6wL5fZSNs6Yra4t8PM98baQ',
    appId: '1:493268505144:web:0340908b6410673a2fcccd',
    messagingSenderId: '493268505144',
    projectId: 'mytodo-f50b8',
    authDomain: 'mytodo-f50b8.firebaseapp.com',
    storageBucket: 'mytodo-f50b8.appspot.com',
    measurementId: 'G-62EQGZBY89',
  );
}
